export enum eServerPacketCommand {
  Sync = "sync",
  Status = "status",

  Connect = "init",
  DeleteGame = "deleteGame",
  UpdateGame = "updateGame",
  ObserveGame = "observeGame",
  RegisterGame = "registerGame",
  UnRegisterGame = "unregisterGame",
  ReBuyRegister = "reBuyRegister",
  CreateTable = "createTable",
  SitTable = "sitTable",
  NextPlayNow = "nextPlayNow",
  RewardPlayNow = "rewardPlayNow",
  AddOn = "addOn",
  CancelGame = "cancelGame",

  // Multi Table Command
  StartTable = "startTable",
  UpdateGameConfig = "updateGameConfig",
  StartHand = "startHand",
  FinishHand = "finishHand",
  EndTable = "endTable",
  // UpdateEntry = "updateEntry",
  UnSitMovePlayer = "unsitMovePlayer",
  SitMovePlayer = "sitMovePlayer",
  CompleteMoved = "completeMoved",
  SitOutPlayer = "sitoutPlayer",
  TableSync = "tableSync",
  TableShuffle = "tableShuffle",
  TableWaitState = "TableWaitState",
  FinalTable = "finalTable",
  CreateFinalTable = "createFinalTable",
  ForceTableStart = "forceTableStart",
  ForceSync = "forceSync",
}
